// Code generated by "stringer -linecomment -type BasicType"; DO NOT EDIT.

package ctype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BasicTypeVoid-1]
	_ = x[BasicTypeChar-2]
	_ = x[BasicTypeSChar-3]
	_ = x[BasicTypeUChar-4]
	_ = x[BasicTypeShort-5]
	_ = x[BasicTypeShortInt-6]
	_ = x[BasicTypeSShort-7]
	_ = x[BasicTypeSShortInt-8]
	_ = x[BasicTypeUShort-9]
	_ = x[BasicTypeUShortInt-10]
	_ = x[BasicTypeInt-11]
	_ = x[BasicTypeSigned-12]
	_ = x[BasicTypeSInt-13]
	_ = x[BasicTypeUnsigned-14]
	_ = x[BasicTypeUInt-15]
	_ = x[BasicTypeLong-16]
	_ = x[BasicTypeLongInt-17]
	_ = x[BasicTypeSLong-18]
	_ = x[BasicTypeSLongInt-19]
	_ = x[BasicTypeULong-20]
	_ = x[BasicTypeULongInt-21]
	_ = x[BasicTypeLongLong-22]
	_ = x[BasicTypeLongLongInt-23]
	_ = x[BasicTypeSLongLong-24]
	_ = x[BasicTypeSLongLongInt-25]
	_ = x[BasicTypeULongLong-26]
	_ = x[BasicTypeULongLongInt-27]
	_ = x[BasicTypeFloat-28]
	_ = x[BasicTypeDouble-29]
	_ = x[BasicTypeLongDouble-30]
}

const _BasicType_name = "voidcharsigned charunsigned charshortshort intsigned shortsigned short intunsigned shortunsigned short intintsignedsigned intunsignedunsigned intlonglong intsigned longsigned long intunsigned longunsigned long intlong longlong long intsigned long longsigned long long intunsigned long longunsigned long long intfloatdoublelong double"

var _BasicType_index = [...]uint16{0, 4, 8, 19, 32, 37, 46, 58, 74, 88, 106, 109, 115, 125, 133, 145, 149, 157, 168, 183, 196, 213, 222, 235, 251, 271, 289, 311, 316, 322, 333}

func (i BasicType) String() string {
	i -= 1
	if i >= BasicType(len(_BasicType_index)-1) {
		return "BasicType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BasicType_name[_BasicType_index[i]:_BasicType_index[i+1]]
}
