// Code generated by "stringer -linecomment -type CallingConv"; DO NOT EDIT.

package ctype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CallConvFastCall-1]
	_ = x[CallConvStdCall-2]
}

const _CallingConv_name = "__fastcall__stdcall"

var _CallingConv_index = [...]uint8{0, 10, 19}

func (i CallingConv) String() string {
	i -= 1
	if i >= CallingConv(len(_CallingConv_index)-1) {
		return "CallingConv(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CallingConv_name[_CallingConv_index[i]:_CallingConv_index[i+1]]
}
